# Model for recomendations solutions on drainage.

1. Postarać się dodać tagi z klasami zlewni

## 1. Import libraries

In [1]:
import swmmio
import pyswmm
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Normalization, Input
from tensorflow.keras.callbacks import EarlyStopping


# desired_width = 500
# pd.set_option("display.width", desired_width)
# np.set_printoptions(linewidth=desired_width)
# pd.set_option("display.max_columns", 30)
import pprint
pd.set_option('display.max_columns', None)
# Ustawienie maksymalnej ilości wyświetlanych wierszy
pd.set_option('display.max_rows', None)


## 2. Recomendation classes

In [2]:
classes = pd.DataFrame(
    data={
        "classes": [
            "valid",
            "diameter_increase",
            "diameter_reduction",
            "slope_increase",
            "slope_reduction",
            "depth_increase",
            "depth_reduction",
            "pump",
            "tank",
            "seepage_boxes",
        ]
    }
)
classes


classes
0               valid
1   diameter_increase
2  diameter_reduction
3      slope_increase
4     slope_reduction
5      depth_increase
6     depth_reduction
7                pump
8                tank
9       seepage_boxes

## 3. Get data

In [3]:
import pandas as pd
import swmmio
import pyswmm
from sa.core.data import DataManager

diameter_01 = R"C:\Users\Dell\Documents\Git\stormwater-analysis\stormwater_analysis\recomendations\diameter\01_diameter.inp"
recomendations_01 = []


model = DataManager(in_file_path=diameter_01, include_rpt=True)
model.enter()
with pyswmm.Simulation(model.inp.path) as sim:
    for _ in sim:
        pass

print(model.df_conduits.columns)
print(model.df_conduits)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step


TypeError: 'bool' object is not subscriptable

### 3.1. Select columns for training

In [ ]:
dataset = model.df_conduits[["ValMaxFill", "ValMaxV", "ValMinV", "ValMaxSlope", "ValMinSlope", "ValDepth", "ValCoverage", "isMinDiameter", "Tag"]]
# model.df_conduits.drop([
#     "MaxDay", "InletNode", "OutletNode", "MaxHr",
#      "InletNodeInvert",  "OutletNodeInvert",  "UpstreamInvert", "DownstreamInvert", "MaxFlow",
#      "InletMaxDepth", "OutletMaxDepth", "InletGroundElevation", "OutletGroundElevation", "InletGroundCover", "OutletGroundCover",
#                         ], inplace=True, axis=1)
print(dataset)
# categories = ["diameter_reduction", "valid", "depth_increase"]

NameError: name 'model' is not defined

### 3.2. Categories 

### 3.3. Classification conduits to categories

In [ ]:
dataset = dataset.reset_index(drop=True)
X = dataset.drop("Tag", axis=1)
y = dataset["Tag"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

y_train = pd.get_dummies(y_train)
y_test = pd.get_dummies(y_test)
print(y_train, y_test)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

NameError: name 'dataset' is not defined

## 6. Build the model

In [ ]:
from keras.regularizers import l2

model = Sequential()
model.add(Dense(units=X_train.shape[1], activation='relu', input_dim=X_train.shape[1], kernel_regularizer=l2(0.01)))
model.add(Dropout(0.2))
model.add(Dense(8, activation='relu', kernel_regularizer=l2(0.01)))
model.add(Dropout(0.2))
model.add(Dense(units=y_train.shape[1], activation='softmax'))

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)
history = model.fit(
    x=X_train,
    y=y_train,
    epochs=100,
    validation_data=(X_test, y_test),
    validation_split=0.2,
    verbose=1,
    batch_size=16,
    callbacks=[EarlyStopping(monitor='val_loss', patience=10)]
)


Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.6250 - loss: 0.8432 - val_accuracy: 0.5000 - val_loss: 0.8542
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.6250 - loss: 0.8424 - val_accuracy: 0.5000 - val_loss: 0.8541
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.6250 - loss: 0.8389 - val_accuracy: 0.5000 - val_loss: 0.8539
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.5000 - loss: 0.8414 - val_accuracy: 0.5000 - val_loss: 0.8537
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.6250 - loss: 0.8398 - val_accuracy: 0.5000 - val_loss: 0.8535
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.6250 - loss: 0.8291 - val_accuracy: 0.5000 - val_loss: 0.8534
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - accuracy: 0.6250 - loss: 0.8357 - val_accuracy: 0.5000 - val_loss: 0.8532
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.6250 - loss: 0.8283 - val_accuracy: 0.5000 - val_loss:

## 7. Evaluate model

In [ ]:
# Evaluate ANN model
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test set accuracy: {accuracy:.3f}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.8486
Test set accuracy: 0.500


In [ ]:
# model.predict(X_test)
y_pred = model.predict(X_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step


In [ ]:
metrics = pd.DataFrame(history.history)
metrics['epoch'] = history.epoch
metrics

accuracy      loss  val_accuracy  val_loss  epoch
0      0.625  0.843179           0.5  0.854182      0
1      0.625  0.842435           0.5  0.854064      1
2      0.625  0.838888           0.5  0.853940      2
3      0.500  0.841357           0.5  0.853721      3
4      0.625  0.839848           0.5  0.853509      4
5      0.625  0.829110           0.5  0.853357      5
6      0.625  0.835673           0.5  0.853228      6
7      0.625  0.828294           0.5  0.853159      7
8      0.625  0.823886           0.5  0.853156      8
9      0.500  0.849706           0.5  0.852991      9
10     0.625  0.831325           0.5  0.852806     10
11     0.625  0.835010           0.5  0.852596     11
12     0.625  0.829920           0.5  0.852394     12
13     0.625  0.813159           0.5  0.852246     13
14     0.625  0.822075           0.5  0.852114     14
15     0.625  0.830842           0.5  0.851984     15
16     0.625  0.817114           0.5  0.851669     16
17     0.625  0.819342           0.5  0.851363     17
18     0.625  0.819505           0.5  0.851087     18
19     0.625  0.814169           0.5  0.850820     19
20     0.625  0.818549           0.5  0.850554     20
21     0.625  0.812954           0.5  0.850303     21
22     0.625  0.811487           0.5  0.850080     22
23     0.625  0.801942           0.5  0.849890     23
24     0.625  0.806057           0.5  0.849707     24
25     0.625  0.810875           0.5  0.849548     25
26     0.625  0.822651           0.5  0.849360     26
27     0.625  0.817883           0.5  0.849178     27
28     0.625  0.813940           0.5  0.849010     28
29     0.625  0.813949           0.5  0.848843     29
30     0.625  0.803719           0.5  0.848701     30
31     0.625  0.801688           0.5  0.848581     31
32     0.625  0.802412           0.5  0.848476     32
33     0.625  0.801930           0.5  0.848375     33
34     0.625  0.805607           0.5  0.848290     34
35     0.625  0.797209           0.5  0.848230     35
36     0.625  0.808254           0.5  0.848170     36
37     0.625  0.809006           0.5  0.848100     37
38     0.625  0.801016           0.5  0.848049     38
39     0.625  0.773560           0.5  0.848047     39
40     0.625  0.800146           0.5  0.848055     40
41     0.625  0.808288           0.5  0.848035     41
42     0.625  0.804445           0.5  0.848009     42
43     0.625  0.809251           0.5  0.847966     43
44     0.625  0.780257           0.5  0.847951     44
45     0.625  0.811225           0.5  0.847904     45
46     0.625  0.771818           0.5  0.847912     46
47     0.625  0.804194           0.5  0.847906     47
48     0.625  0.809251           0.5  0.847858     48
49     0.625  0.766922           0.5  0.847867     49
50     0.625  0.793614           0.5  0.847887     50
51     0.625  0.807566           0.5  0.847853     51
52     0.625  0.811876           0.5  0.847707     52
53     0.625  0.783005           0.5  0.847585     53
54     0.625  0.794595           0.5  0.847454     54
55     0.625  0.755499           0.5  0.847406     55
56     0.625  0.820877           0.5  0.847306     56
57     0.625  0.781201           0.5  0.847227     57
58     0.625  0.791134           0.5  0.847160     58
59     0.625  0.769145           0.5  0.847139     59
60     0.625  0.784593           0.5  0.847135     60
61     0.625  0.795839           0.5  0.847088     61
62     0.625  0.761420           0.5  0.847108     62
63     0.625  0.763501           0.5  0.847167     63
64     0.625  0.765072           0.5  0.847266     64
65     0.625  0.754818           0.5  0.847418     65
66     0.625  0.784315           0.5  0.847548     66
67     0.625  0.754528           0.5  0.847725     67
68     0.625  0.760269           0.5  0.847934     68
69     0.625  0.768032           0.5  0.848155     69
70     0.625  0.770558           0.5  0.848370     70
71     0.625  0.742800           0.5  0.848644     71

In [ ]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

fig = make_subplots(rows=1, cols=2)
fig.add_trace(go.Scatter(x=metrics['epoch'], y=metrics['accuracy'], name='accuracy'), row=1, col=1)
fig.add_trace(go.Scatter(x=metrics['epoch'], y=metrics['loss'], name='loss'), row=1, col=2)
fig.add_trace(go.Scatter(x=metrics['epoch'], y=metrics['val_accuracy'], name='val_accuracy'), row=1, col=1)
fig.add_trace(go.Scatter(x=metrics['epoch'], y=metrics['val_loss'], name='val_loss'), row=1, col=2)

fig.update_xaxes(title_text='epochs')
fig.update_yaxes(title_text='accuracy', row=1, col=1)
fig.update_yaxes(title_text='loss', row=1, col=2)
fig.update_layout(width=1000, title='Accuracy and Loss')
fig.show()

In [ ]:
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)
print(test_acc)

0.5


## 8. Predictions

In [ ]:
predictions = model.predict(X_test)
predictions

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step


array([[0.5504575 , 0.44954252],
       [0.58029795, 0.41970205]], dtype=float32)

In [ ]:
predictions_df = pd.DataFrame(predictions)
predictions_df

0         1
0  0.550457  0.449543
1  0.580298  0.419702

In [ ]:
predictions_cls = predictions.argmax(axis=-1)
predictions_cls

array([0, 0], dtype=int64)

# Zapisanie modelu

In [ ]:
model.save(R'C:\Users\Dell\Documents\Git\stormwater-analysis\stormwater_analysis\recomendations\recomendations.keras')


In [ ]:
from tensorflow import keras
model = keras.models.load_model(R'C:\Users\Dell\Documents\Git\stormwater-analysis\stormwater_analysis\recomendations\recomendations.keras')
pred = model.predict(X_test)
pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step


array([[0.5504575 , 0.44954252],
       [0.58029795, 0.41970205]], dtype=float32)